### ISSUE TITLE
Internal Server Error for url: https://kagi.com/api/v0/search...

### ISSUE THREAD

**Issue by cstromblad** [kagisearch/kagiapi#3]
Not quite sure what else to post?

Have used the API "manually" but then discovered this python package, but... it doesn't work? Have also tried Enrich and FastGPT with 500 and 502 error messages.

Update: 5 minutes later, it appears to be working! This issue can thus be closed without further action!

**Comment by vprelovac** [comment]
This is related to infra issues we are having now https://status.kagi.com/issues/2024-01-12-kagi-down-on-some-regions/
